Workaround to avoid errors that cause plugin to crash on Java 11
When running this plugin under Java 11, calls to event_processor_host.getHostContext.getEventHubPath
 can fail with `org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `getEventHubPath'`

This can be avoided by removing the calls to this method, which is only used in logging calls and is
 unnecessary - the value is the same as that held in the `event_hub_name`